environment: test
host_suffix: test

clusters:
  sample-cluster:
    image: 9ec5c0c-a941-11e2-a7dc-57a6b041988f
    flavor: "g3-highmemory-17.125-smartos"
    distro: smartos-base64
    networks: "42325ea0-eb62-44c1-8eb6-0af3e2f83abc,c8cde927-6277-49ca-82a3-741e8b23b02f"
    host_prefix: sample-cluster
    run_list: "role[joyent]"
    host_sequence: 1..2

